import { createEmbed } from '../../shared/discord-helpers.js';
import { chunkText, formatDateInTimeZone } from '../../shared/utils.js';

const TOKEN_PRICES = {
  'deepseek-chat': {
    input: 0.0005,
    output: 0.0025
  }
};

const DEFAULT_TOKEN_PRICE = {
  input: 0.001,
  output: 0.002
};

export class SummaryService {
  constructor(context) {
    this.context = context;
  }

  calculateTokenCost(model, promptTokens, completionTokens) {
    const prices = TOKEN_PRICES[model] ?? DEFAULT_TOKEN_PRICE;
    const inputCost = (promptTokens / 1000) * prices.input;
    const outputCost = (completionTokens / 1000) * prices.output;
    return inputCost + outputCost;
  }

  async recordDeepseekTokenUsage(model, usage, operation) {
    if (!usage) {
      return;
    }

    const promptTokens = usage.prompt_tokens || 0;
    const completionTokens = usage.completion_tokens || 0;
    const totalTokens = usage.total_tokens || (promptTokens + completionTokens);
    const now = new Date();

    await this.context.database.tokenUsage.update((store) => {
      store.entries.push({
        timestamp: now.toISOString(),
        date: now.toISOString().slice(0, 10),
        time: now.toISOString().slice(11, 19),
        provider: 'deepseek',
        model,
        operation,
        prompt_tokens: promptTokens,
        completion_tokens: completionTokens,
        total_tokens: totalTokens,
        cost_usd: this.calculateTokenCost(model, promptTokens, completionTokens)
      });
      return store;
    });
  }

  buildSummaryChunks(summary) {
    if (!summary) {
      return ['Shrnutí není k dispozici.'];
    }

    if (summary.length <= 4096) {
      return [summary];
    }

    const paragraphs = summary.split('\n\n');
    const chunks = [];
    let currentChunk = '';

    for (const paragraph of paragraphs) {
      if (currentChunk && currentChunk.length + paragraph.length + 2 > 4096) {
        chunks.push(currentChunk);
        currentChunk = '';
      }

      if (paragraph.length > 4096) {
        if (currentChunk) {
          chunks.push(currentChunk);
          currentChunk = '';
        }

        for (const chunk of chunkText(paragraph, 4096)) {
          chunks.push(chunk);
        }
        continue;
      }

      currentChunk = currentChunk ? `${currentChunk}\n\n${paragraph}` : paragraph;
    }

    if (currentChunk) {
      chunks.push(currentChunk);
    }

    return chunks;
  }

  async captureMessage(message) {
    const config = await this.context.configStore.get();

    if (
      !config.features.summary ||
      !config.summary.enabled ||
      !message.guild ||
      message.author.bot ||
      message.channelId !== config.summary.sourceChannelId
    ) {
      return false;
    }

    await this.context.database.chatMessages.update((store) => {
      store.messages.push({
        user_id: message.author.id,
        username: message.author.username,
        display_name: message.member?.displayName || message.author.username,
        channel_id: message.channelId,
        channel_name: message.channel.name,
        content: message.content,
        timestamp: message.createdAt.toISOString(),
        message_id: message.id,
        has_attachments: message.attachments.size > 0,
        has_embeds: message.embeds.length > 0,
        jump_url: message.url
      });
      return store;
    });

    return true;
  }

  async getMessagesByDate(dateString) {
    const store = await this.context.database.chatMessages.read();
    return store.messages.filter((message) => message.timestamp.slice(0, 10) === dateString);
  }

  async getStoredDailySummary(dateString) {
    return this.context.database.getDailySummaryStore(dateString).read();
  }

  async generateDailySummary(dateString, options = {}) {
    const config = await this.context.configStore.get();
    const store = this.context.database.getDailySummaryStore(dateString);
    const existing = await store.read();

    if (existing.summary && !options.force) {
      return existing;
    }

    const messages = await this.getMessagesByDate(dateString);
    const result = await this.summarizeMessages(messages, config.summary.provider);

    const nextValue = {
      date: dateString,
      message_count: messages.length,
      summary: result.summary,
      timestamp: new Date().toISOString(),
      topic_message_ids: result.topicMessageIds,
      auto_generated: Boolean(options.autoGenerated),
      manual: Boolean(options.manual),
      requested_by: options.requestedBy || null
    };

    await store.write(nextValue);
    await this.purgeOldMessages(config.summary.retentionDays);
    return nextValue;
  }

  async summarizeMessages(messages, _provider) {
    if (!messages.length) {
      return {
        summary: 'Ten den se v summary kanálu nic neodehrálo.',
        topicMessageIds: []
      };
    }

    if (!this.context.env.DEEPSEEK_API_KEY) {
      return this.fallbackSummary(messages);
    }

    const messageTexts = [];

    for (const message of messages) {
      const content = message.content?.trim();
      if (!content) {
        continue;
      }

      const timestamp = message.timestamp.slice(0, 19);
      messageTexts.push(`[${timestamp}] ${message.display_name}: ${content}`);
    }

    const systemPrompt = [
      'Jsi kreativní a zábavný asistent, který vytváří denní shrnutí diskuzí z Discord chatu.',
      'Tvým úkolem je analyzovat zprávy a vytvořit poutavé a čtivé shrnutí hlavních témat, která se v chatu probírala.',
      'Shrnutí musí být v češtině, rozdělené podle témat, ale psané neformálním a zábavným způsobem.',
      'Pro každé téma identifikuj první zprávu, která toto téma začíná, a označ ji jako `[TOPIC_START:index]`, kde index je pořadové číslo zprávy v seznamu od 0.',
      'Zahrň odkazy, pokud se v chatu nějaké vyskytly.',
      'Místo suchého reportu se zaměř na to, aby shrnutí bylo poutavé, jako bys vyprávěl příběh.',
      'Datum v hlavičce formátuj jako `D. M. YYYY`.',
      'Na konci přidej krátký a vtipný souhrn celého dne.'
    ].join(' ');

    const userPrompt = [
      `Zde jsou zprávy z Discord chatu ze dne ${messages[0].timestamp.slice(0, 10)}.`,
      'Vytvoř zábavné a poutavé shrnutí hlavních témat, která se probírala.',
      'Rozděl shrnutí podle témat, ale piš ho jako příběh, ne jako suchý report.',
      'Pro každé téma označ první zprávu markerem `[TOPIC_START:index]`.',
      'Pokud se v chatu stalo něco obzvlášť vtipného nebo výrazného, nezapomeň to zmínit.',
      `Formát hlavičky musí být přesně: "📊 Shrnutí chatu za ${messages[0].timestamp.slice(0, 10)}\\nShrnutí diskuzí z Discord chatu (D. M. YYYY)\\n---"`,
      '',
      messageTexts.join('\n')
    ].join('\n');

    const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.context.env.DEEPSEEK_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ]
      })
    });

    if (!response.ok) {
      this.context.logger.warn({ status: response.status }, 'DeepSeek vrátil chybu, padám na fallback.');
      return this.fallbackSummary(messages);
    }

    const payload = await response.json();
    const summary = payload.choices?.[0]?.message?.content;

    if (!summary) {
      return this.fallbackSummary(messages);
    }

    await this.recordDeepseekTokenUsage(payload.model || 'deepseek-chat', payload.usage, 'summary');

    return {
      summary: this.replaceTopicMarkers(summary, messages),
      topicMessageIds: this.extractTopicMessageIds(summary, messages)
    };
  }

  fallbackSummary(messages) {
    const topUsers = new Map();

    for (const message of messages) {
      topUsers.set(message.display_name, (topUsers.get(message.display_name) ?? 0) + 1);
    }

    const leaders = [...topUsers.entries()]
      .sort((left, right) => right[1] - left[1])
      .slice(0, 5)
      .map(([name, count]) => `${name} (${count})`)
      .join(', ');

    const sample = messages
      .slice(-5)
      .map((message) => `- ${message.display_name}: ${message.content || '(priloha)'}`)
      .join('\n');

    return {
      summary: [
        `Zpráv: ${messages.length}`,
        `Nejaktivnější: ${leaders || 'nikdo'}`,
        '',
        'Poslední zachycené body:',
        sample
      ].join('\n'),
      topicMessageIds: messages.slice(0, 3).map((message) => message.message_id)
    };
  }

  replaceTopicMarkers(text, messages) {
    return text.replace(/\[TOPIC_START:(\d+)\]/gu, (_, indexText) => {
      const message = messages[Number(indexText)];
      return message?.jump_url ? `[téma](${message.jump_url})` : '';
    });
  }

  extractTopicMessageIds(text, messages) {
    const output = [];

    for (const match of text.matchAll(/\[TOPIC_START:(\d+)\]/gu)) {
      const message = messages[Number(match[1])];
      if (message) {
        output.push(message.message_id);
      }
    }

    return output;
  }

  async sendSummaryToChannel(guild, summaryRecord, targetChannelId) {
    const channelId = targetChannelId || (await this.context.configStore.get()).summary.targetChannelId;
    const channel = guild.channels.cache.get(channelId) ?? await guild.channels.fetch(channelId).catch(() => null);

    if (!channel?.isTextBased?.()) {
      return false;
    }

    const chunks = this.buildSummaryChunks(summaryRecord.summary);

    for (const [index, chunk] of chunks.entries()) {
      await channel.send({
        embeds: [
          createEmbed({
            description: chunk,
            footer: index === 0 ? `Celkem zpráv: ${summaryRecord.message_count}` : undefined
          })
        ]
      });
    }

    return true;
  }

  async summarizeRecentForUser(member, count) {
    const config = await this.context.configStore.get();
    const cooldownUntil = this.context.runtime.summaryCooldowns.get(member.id);

    if (!member.permissions.has('Administrator') && cooldownUntil && cooldownUntil > Date.now()) {
      throw new Error('Cooldown na DM shrnutí ještě běží.');
    }

    const store = await this.context.database.chatMessages.read();
    const messages = store.messages.slice(-count);
    const result = await this.summarizeMessages(messages, config.summary.provider);
    this.context.runtime.summaryCooldowns.set(member.id, Date.now() + config.summary.cooldownHours * 3_600_000);
    return {
      ...result,
      messageCount: messages.length
    };
  }

  async sendSummaryToUserDm(user, summaryRecord) {
    const dm = await user.createDM();
    const chunks = this.buildSummaryChunks(summaryRecord.summary);

    for (const [index, chunk] of chunks.entries()) {
      await dm.send({
        embeds: [
          createEmbed({
            description: chunk,
            footer: index === 0 ? `Celkem zpráv: ${summaryRecord.messageCount ?? summaryRecord.message_count ?? 0}` : undefined
          })
        ]
      });
    }
  }

  async getTodayMessageCount() {
    const date = formatDateInTimeZone(new Date(), this.context.env.TIMEZONE);
    const messages = await this.getMessagesByDate(date);
    return messages.length;
  }

  async purgeOldMessages(retentionDays) {
    const threshold = Date.now() - retentionDays * 86_400_000;

    await this.context.database.chatMessages.update((store) => {
      store.messages = store.messages.filter((message) => new Date(message.timestamp).getTime() >= threshold);
      return store;
    });
  }
}
