import { createEmbed } from '../../shared/discord-helpers.js';
import { chunkText, formatDateInTimeZone } from '../../shared/utils.js';

export class SummaryService {
  constructor(context) {
    this.context = context;
  }

  async captureMessage(message) {
    const config = await this.context.configStore.get();

    if (
      !config.features.summary ||
      !config.summary.enabled ||
      !message.guild ||
      message.author.bot ||
      message.channelId !== config.summary.sourceChannelId
    ) {
      return false;
    }

    await this.context.database.chatMessages.update((store) => {
      store.messages.push({
        user_id: message.author.id,
        username: message.author.username,
        display_name: message.member?.displayName || message.author.username,
        channel_id: message.channelId,
        channel_name: message.channel.name,
        content: message.content,
        timestamp: message.createdAt.toISOString(),
        message_id: message.id,
        has_attachments: message.attachments.size > 0,
        has_embeds: message.embeds.length > 0,
        jump_url: message.url
      });
      return store;
    });

    return true;
  }

  async getMessagesByDate(dateString) {
    const store = await this.context.database.chatMessages.read();
    return store.messages.filter((message) => message.timestamp.slice(0, 10) === dateString);
  }

  async getStoredDailySummary(dateString) {
    return this.context.database.getDailySummaryStore(dateString).read();
  }

  async generateDailySummary(dateString, options = {}) {
    const config = await this.context.configStore.get();
    const store = this.context.database.getDailySummaryStore(dateString);
    const existing = await store.read();

    if (existing.summary && !options.force) {
      return existing;
    }

    const messages = await this.getMessagesByDate(dateString);
    const result = await this.summarizeMessages(messages, config.summary.provider);

    const nextValue = {
      date: dateString,
      message_count: messages.length,
      summary: result.summary,
      timestamp: new Date().toISOString(),
      topic_message_ids: result.topicMessageIds,
      auto_generated: Boolean(options.autoGenerated),
      manual: Boolean(options.manual),
      requested_by: options.requestedBy || null
    };

    await store.write(nextValue);
    await this.purgeOldMessages(config.summary.retentionDays);
    return nextValue;
  }

  async summarizeMessages(messages) {
    if (!messages.length) {
      return {
        summary: 'Ten den se v summary kanálu nic neodehrálo.',
        topicMessageIds: []
      };
    }

    if (!this.context.env.DEEPSEEK_API_KEY) {
      return this.fallbackSummary(messages);
    }

    const prompt = [
      'Udělej věcné denní shrnutí Discord chatu v češtině.',
      'Použij markery [TOPIC_START:index] pro začátek témat.',
      'Buď stručný, ale výstižný.',
      '',
      ...messages.map((message, index) => `[${index}] ${message.display_name}: ${message.content || '(priloha)'}`)
    ].join('\n');

    const response = await fetch('https://api.deepseek.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.context.env.DEEPSEEK_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [
          { role: 'system', content: 'Jsi analytik Discord komunity.' },
          { role: 'user', content: prompt }
        ]
      })
    });

    if (!response.ok) {
      this.context.logger.warn({ status: response.status }, 'DeepSeek vrátil chybu, padám na fallback.');
      return this.fallbackSummary(messages);
    }

    const payload = await response.json();
    const summary = payload.choices?.[0]?.message?.content;

    if (!summary) {
      return this.fallbackSummary(messages);
    }

    await this.context.database.tokenUsage.update((store) => {
      store.entries.push({
        timestamp: new Date().toISOString(),
        date: new Date().toISOString().slice(0, 10),
        time: new Date().toISOString().slice(11, 19),
        provider: 'deepseek',
        model: 'deepseek-chat',
        operation: 'summary',
        prompt_tokens: payload.usage?.prompt_tokens || 0,
        completion_tokens: payload.usage?.completion_tokens || 0,
        total_tokens: payload.usage?.total_tokens || 0,
        cost_usd: 0
      });
      return store;
    });

    return {
      summary: this.replaceTopicMarkers(summary, messages),
      topicMessageIds: this.extractTopicMessageIds(summary, messages)
    };
  }

  fallbackSummary(messages) {
    const topUsers = new Map();

    for (const message of messages) {
      topUsers.set(message.display_name, (topUsers.get(message.display_name) ?? 0) + 1);
    }

    const leaders = [...topUsers.entries()]
      .sort((left, right) => right[1] - left[1])
      .slice(0, 5)
      .map(([name, count]) => `${name} (${count})`)
      .join(', ');

    const sample = messages
      .slice(-5)
      .map((message) => `- ${message.display_name}: ${message.content || '(priloha)'}`)
      .join('\n');

    return {
      summary: [
        `Zpráv: ${messages.length}`,
        `Nejaktivnější: ${leaders || 'nikdo'}`,
        '',
        'Poslední zachycené body:',
        sample
      ].join('\n'),
      topicMessageIds: messages.slice(0, 3).map((message) => message.message_id)
    };
  }

  replaceTopicMarkers(text, messages) {
    return text.replace(/\[TOPIC_START:(\d+)\]/gu, (_, indexText) => {
      const message = messages[Number(indexText)];
      return message?.jump_url ?? '';
    });
  }

  extractTopicMessageIds(text, messages) {
    const output = [];

    for (const match of text.matchAll(/\[TOPIC_START:(\d+)\]/gu)) {
      const message = messages[Number(match[1])];
      if (message) {
        output.push(message.message_id);
      }
    }

    return output;
  }

  async sendSummaryToChannel(guild, summaryRecord, targetChannelId) {
    const channelId = targetChannelId || (await this.context.configStore.get()).summary.targetChannelId;
    const channel = guild.channels.cache.get(channelId) ?? await guild.channels.fetch(channelId).catch(() => null);

    if (!channel?.isTextBased?.()) {
      return false;
    }

    for (const chunk of chunkText(summaryRecord.summary, 1900)) {
      await channel.send({
        embeds: [
          createEmbed({
            title: `Denní shrnutí ${summaryRecord.date}`,
            description: chunk
          })
        ]
      });
    }

    return true;
  }

  async summarizeRecentForUser(member, count) {
    const config = await this.context.configStore.get();
    const cooldownUntil = this.context.runtime.summaryCooldowns.get(member.id);

    if (!member.permissions.has('Administrator') && cooldownUntil && cooldownUntil > Date.now()) {
      throw new Error('Cooldown na DM shrnutí ještě běží.');
    }

    const store = await this.context.database.chatMessages.read();
    const messages = store.messages.slice(-count);
    const result = await this.summarizeMessages(messages, config.summary.provider);
    this.context.runtime.summaryCooldowns.set(member.id, Date.now() + config.summary.cooldownHours * 3_600_000);
    return result;
  }

  async getTodayMessageCount() {
    const date = formatDateInTimeZone(new Date(), this.context.env.TIMEZONE);
    const messages = await this.getMessagesByDate(date);
    return messages.length;
  }

  async purgeOldMessages(retentionDays) {
    const threshold = Date.now() - retentionDays * 86_400_000;

    await this.context.database.chatMessages.update((store) => {
      store.messages = store.messages.filter((message) => new Date(message.timestamp).getTime() >= threshold);
      return store;
    });
  }
}
